// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, commented_by, parent_id, body)
VALUES ($1, $2, $3, $4)
RETURNING comment_id, post_id, commented_by, parent_id, body, created_at, status
`

type CreateCommentParams struct {
	PostID      int64
	CommentedBy int64
	ParentID    pgtype.Int8
	Body        string
}

type CreateCommentRow struct {
	CommentID   int64
	PostID      int64
	CommentedBy int64
	ParentID    pgtype.Int8
	Body        string
	CreatedAt   pgtype.Timestamptz
	Status      string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.CommentedBy,
		arg.ParentID,
		arg.Body,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.CommentID,
		&i.PostID,
		&i.CommentedBy,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT comment_id, post_id, commented_by, parent_id, body, created_at, edited_at, status
FROM comments
WHERE comment_id = $1
`

type GetCommentRow struct {
	CommentID   int64
	PostID      int64
	CommentedBy int64
	ParentID    pgtype.Int8
	Body        string
	CreatedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
	Status      string
}

func (q *Queries) GetComment(ctx context.Context, commentID int64) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, commentID)
	var i GetCommentRow
	err := row.Scan(
		&i.CommentID,
		&i.PostID,
		&i.CommentedBy,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Status,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT
    c.comment_id,
    c.post_id,
    c.commented_by,
    c.parent_id,
    c.body,
    c.created_at,
    c.edited_at,
    c.status,
    u.username
FROM comments c
JOIN users u ON c.commented_by = u.user_id
WHERE c.post_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByPostRow struct {
	CommentID   int64
	PostID      int64
	CommentedBy int64
	ParentID    pgtype.Int8
	Body        string
	CreatedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
	Status      string
	Username    string
}

func (q *Queries) ListCommentsByPost(ctx context.Context, postID int64) ([]ListCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByPostRow
	for rows.Next() {
		var i ListCommentsByPostRow
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.CommentedBy,
			&i.ParentID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Status,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET body = $2, edited_at = NOW()
WHERE comment_id = $1 AND commented_by = $3
    RETURNING comment_id, body, edited_at
`

type UpdateCommentParams struct {
	CommentID   int64
	Body        string
	CommentedBy int64
}

type UpdateCommentRow struct {
	CommentID int64
	Body      string
	EditedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (UpdateCommentRow, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.CommentID, arg.Body, arg.CommentedBy)
	var i UpdateCommentRow
	err := row.Scan(&i.CommentID, &i.Body, &i.EditedAt)
	return i, err
}
