// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    int64
	Username  string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
}
