// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	CommentID     int64
	PostID        int64
	CommentedBy   int64
	ParentID      pgtype.Int8
	Body          string
	CreatedAt     pgtype.Timestamptz
	EditedAt      pgtype.Timestamptz
	Status        string
	RemovedAt     pgtype.Timestamptz
	RemovedBy     pgtype.Int8
	RemovalReason pgtype.Text
}

type Post struct {
	PostID        int64
	TopicID       int64
	CreatedBy     int64
	Title         string
	Body          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Status        string
	RemovedAt     pgtype.Timestamptz
	RemovedBy     pgtype.Int8
	RemovalReason pgtype.Text
}

type Topic struct {
	TopicID       int64
	CreatedBy     int64
	Name          string
	Description   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Status        string
	RemovedAt     pgtype.Timestamptz
	RemovedBy     pgtype.Int8
	RemovalReason pgtype.Text
	PostCount     pgtype.Int8
}

type User struct {
	UserID       int64
	Username     string
	PasswordHash string
	Bio          string
	CreatedAt    pgtype.Timestamptz
}
