// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (topic_id, created_by, title, body)
VALUES ($1, $2, $3, $4)
RETURNING post_id, topic_id, created_by, title, body, created_at, status
`

type CreatePostParams struct {
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
}

type CreatePostRow struct {
	PostID    int64
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	Status    pgtype.Text
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.TopicID,
		arg.CreatedBy,
		arg.Title,
		arg.Body,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.CreatedBy,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT post_id, topic_id, created_by, title, body, created_at, status
FROM posts
WHERE post_id = $1
`

type GetPostRow struct {
	PostID    int64
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	Status    pgtype.Text
}

func (q *Queries) GetPost(ctx context.Context, postID int64) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, postID)
	var i GetPostRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.CreatedBy,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const listPostsInTopic = `-- name: ListPostsInTopic :many
SELECT post_id, topic_id, created_by, title, body, created_at, status
FROM posts
WHERE topic_id = $1
ORDER BY created_at DESC
`

type ListPostsInTopicRow struct {
	PostID    int64
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	Status    pgtype.Text
}

func (q *Queries) ListPostsInTopic(ctx context.Context, topicID int64) ([]ListPostsInTopicRow, error) {
	rows, err := q.db.Query(ctx, listPostsInTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsInTopicRow
	for rows.Next() {
		var i ListPostsInTopicRow
		if err := rows.Scan(
			&i.PostID,
			&i.TopicID,
			&i.CreatedBy,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsGlobal = `-- name: SearchPostsGlobal :many
SELECT post_id, topic_id, created_by, title, body, created_at, status
FROM posts
WHERE
    (title ILIKE '%' || $1 || '%' OR body ILIKE '%' || $1 || '%')
    AND status = 'active'
ORDER BY created_at DESC
`

type SearchPostsGlobalRow struct {
	PostID    int64
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	Status    pgtype.Text
}

func (q *Queries) SearchPostsGlobal(ctx context.Context, dollar_1 pgtype.Text) ([]SearchPostsGlobalRow, error) {
	rows, err := q.db.Query(ctx, searchPostsGlobal, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsGlobalRow
	for rows.Next() {
		var i SearchPostsGlobalRow
		if err := rows.Scan(
			&i.PostID,
			&i.TopicID,
			&i.CreatedBy,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsInTopic = `-- name: SearchPostsInTopic :many
SELECT post_id, topic_id, created_by, title, body, created_at, status
FROM posts
WHERE
    topic_id = $1
  AND (title ILIKE '%' || $2 || '%' OR body ILIKE '%' || $2 || '%')
  AND status = 'active'
ORDER BY created_at DESC
`

type SearchPostsInTopicParams struct {
	TopicID int64
	Column2 pgtype.Text
}

type SearchPostsInTopicRow struct {
	PostID    int64
	TopicID   int64
	CreatedBy int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	Status    pgtype.Text
}

func (q *Queries) SearchPostsInTopic(ctx context.Context, arg SearchPostsInTopicParams) ([]SearchPostsInTopicRow, error) {
	rows, err := q.db.Query(ctx, searchPostsInTopic, arg.TopicID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsInTopicRow
	for rows.Next() {
		var i SearchPostsInTopicRow
		if err := rows.Scan(
			&i.PostID,
			&i.TopicID,
			&i.CreatedBy,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
