// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (created_by, name, description)
VALUES ($1, $2, $3)
RETURNING topic_id, created_by, name, description, created_at, status, post_count
`

type CreateTopicParams struct {
	CreatedBy   int64
	Name        string
	Description string
}

type CreateTopicRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      string
	PostCount   int64
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (CreateTopicRow, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.CreatedBy, arg.Name, arg.Description)
	var i CreateTopicRow
	err := row.Scan(
		&i.TopicID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
		&i.PostCount,
	)
	return i, err
}

const decrementPostCount = `-- name: DecrementPostCount :exec
UPDATE topics
SET post_count = post_count - 1
WHERE topic_id = $1
`

func (q *Queries) DecrementPostCount(ctx context.Context, topicID int64) error {
	_, err := q.db.Exec(ctx, decrementPostCount, topicID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :one
UPDATE topics
SET status = 'removed', removed_at = NOW(), removed_by = $2
WHERE topic_id = $1 AND created_by = $3
RETURNING topic_id
`

type DeleteTopicParams struct {
	TopicID   int64
	RemovedBy pgtype.Int8
	CreatedBy int64
}

func (q *Queries) DeleteTopic(ctx context.Context, arg DeleteTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteTopic, arg.TopicID, arg.RemovedBy, arg.CreatedBy)
	var topic_id int64
	err := row.Scan(&topic_id)
	return topic_id, err
}

const getTopic = `-- name: GetTopic :one
SELECT topic_id, created_by, name, description, created_at, status, post_count
FROM topics
WHERE topic_id = $1
`

type GetTopicRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      string
	PostCount   int64
}

func (q *Queries) GetTopic(ctx context.Context, topicID int64) (GetTopicRow, error) {
	row := q.db.QueryRow(ctx, getTopic, topicID)
	var i GetTopicRow
	err := row.Scan(
		&i.TopicID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
		&i.PostCount,
	)
	return i, err
}

const incrementPostCount = `-- name: IncrementPostCount :exec
UPDATE topics
SET post_count = post_count + 1
WHERE topic_id = $1
`

func (q *Queries) IncrementPostCount(ctx context.Context, topicID int64) error {
	_, err := q.db.Exec(ctx, incrementPostCount, topicID)
	return err
}

const listTopics = `-- name: ListTopics :many
SELECT topic_id, created_by, name, description, created_at, status, post_count
FROM topics
WHERE status = 'active'
ORDER BY created_at DESC
`

type ListTopicsRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      string
	PostCount   int64
}

func (q *Queries) ListTopics(ctx context.Context) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsRow
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.TopicID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Status,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTopics = `-- name: SearchTopics :many
SELECT topic_id, created_by, name, description, created_at, status, post_count
FROM topics
WHERE
    (name ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
    AND status = 'active'
ORDER BY created_at DESC
`

type SearchTopicsRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      string
	PostCount   int64
}

func (q *Queries) SearchTopics(ctx context.Context, dollar_1 pgtype.Text) ([]SearchTopicsRow, error) {
	rows, err := q.db.Query(ctx, searchTopics, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTopicsRow
	for rows.Next() {
		var i SearchTopicsRow
		if err := rows.Scan(
			&i.TopicID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Status,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
