// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (created_by, name, description)
VALUES ($1, $2, $3)
RETURNING topic_id, created_by, name, description, created_at, status
`

type CreateTopicParams struct {
	CreatedBy   int64
	Name        string
	Description string
}

type CreateTopicRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      pgtype.Text
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (CreateTopicRow, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.CreatedBy, arg.Name, arg.Description)
	var i CreateTopicRow
	err := row.Scan(
		&i.TopicID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
SELECT topic_id, created_by, name, description, created_at, status
FROM topics
WHERE topic_id = $1
`

type GetTopicRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      pgtype.Text
}

func (q *Queries) GetTopic(ctx context.Context, topicID int64) (GetTopicRow, error) {
	row := q.db.QueryRow(ctx, getTopic, topicID)
	var i GetTopicRow
	err := row.Scan(
		&i.TopicID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT topic_id, created_by, name, description, created_at, status
FROM topics
WHERE status = 'active'
ORDER BY created_at DESC
`

type ListTopicsRow struct {
	TopicID     int64
	CreatedBy   int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	Status      pgtype.Text
}

func (q *Queries) ListTopics(ctx context.Context) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsRow
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.TopicID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
